### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by jgentes** [wrr/connect-wwwhisper#11]
Any thoughts as to when this will be supported? Getting this:

'Error: wwwhipsper requires node version 0.10 or 0.11 or io.js '

I can downgrade Node but other dependencies make 12 the best choice right now.

Thanks, this is an excellent utility and I've been very happy with it. Just recently updated to Node 12.

**Comment by wrr** [comment]
Hi @jgentes no need to downgrade, I'll work on adding support for v12 today.

**Comment by jgentes** [comment]
Awesome, thank you very much.

**Comment by wrr** [comment]
I've pushed new npm that enables Node 0.12. Thank you for reporting the issue!

**Comment by jgentes** [comment]
Awesome, thanks so much!
