### ISSUE TITLE
connect-wwwhisper does not work with connect/express compress middleware

### ISSUE THREAD

**Issue by joegoldbeck** [wrr/connect-wwwhisper#5]
When I use connect-wwwhisper, my routes in which I call res.send work fine, as does all my other middleware such as static. However, if I create a route that calls res.render instead of res.send, I just get a blank 200 response in my client.

**Comment by Danm72** [comment]
Can this iframe switch be accessed from rails?

**Comment by wrr** [comment]
@Danm72 In Rails WWWHISPER_IFRAME environment variable can be used to redefine content of the injected html. To disable the iframe you can set this var to an empty string ''. With Foreman you can do it like this:

    echo "WWWHISPER_IFRAME=''">>.env
